# Generated by Django 3.0.5 on 2020-04-05 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agents',
            options={'verbose_name': 'Agent', 'verbose_name_plural': 'Agents'},
        ),
    ]
