# Generated by Django 3.0.5 on 2020-04-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_auto_20200405_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agents',
            name='image',
            field=models.ImageField(null=True, upload_to='agents/'),
        ),
    ]
