# Generated by Django 3.0.5 on 2020-04-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(default=0, upload_to='property/'),
            preserve_default=False,
        ),
    ]
