# Generated by Django 3.0.5 on 2020-04-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_auto_20200404_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
