# Generated by Django 3.0.5 on 2020-04-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_property_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Sale', 'sale'), ('Rent', 'rent')], max_length=10),
        ),
    ]
