# Generated by Django 3.0.5 on 2020-04-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('sale', 'sale'), ('rent', 'rent')], max_length=20),
        ),
    ]
